name: "mxscript"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: '/'

# Information for the Atom feed
gereksiz:
   author: "Rodrigo"
   email: "mxscript@yahoo.com"
